version: 1

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "Placeholder: GitHub Actions will fill this in"
        LoadBalancerInfo:
          ContainerName: "dev-2g2943-cyd-ecs-container-web"
          ContainerPort: 80
        PlatformVersion: "LATEST"
